#!/bin/sh -x

force=false

if [ "$1" = '-f' ]; then
	echo "Force cleaning the work dir"
	force=true
	shift
fi
name=runner$1

docker ps -a
docker stop $name
docker ps -a
docker rm $name
docker ps -a

if $force; then
	sudo rm -rf work-"$name"
fi

