#!/bin/sh

NAME="runner$nr"
OWNER="btrfs"
REPO="linux"
RURL="https://github.com/$OWNER/$REPO"
IMAGE="ghcr.io/actions/actions-runner:latest"
RHOME="/home/runner"
RWORK="$RHOME/_work"
LWORK="work-$NAME"
LWORKABS=$(readlink -f "$LWORK")

if ! [ -f "runner-pat" ]; then
	echo "ERROR: cannot find the PAT file 'runner-pat' to generate tokens"
	exit 1
fi

GITHUB_PAT=$(cat runner-pat)

#echo $GITHUB_PAT

output=$(
curl	-sS \
	-X POST \
	-H "Accept: application/vnd.github+json" \
	-H "Authorization: Bearer $GITHUB_PAT" \
	-H "X-GitHub-Api-Version: 2026-03-10" \
	https://api.github.com/repos/$OWNER/$REPO/actions/runners/registration-token)

echo RET $?
echo "$output"

if echo "$output" | grep 'status.*401'; then
	echo "Expired token"
	exit 1
fi

echo "$output" | \
sed -n 's/.*"token"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p'
