#!/bin/sh

OWNER="btrfs"
REPO="linux"

type -p jq >& /dev/null || { echo "ERROR: jq not found"; }

if ! [ -f "runner-pat" ]; then
	echo "ERROR: cannot find the PAT file 'runner-pat' to generate tokens"
	exit 1
fi

GITHUB_PAT=$(cat runner-pat)

output=$(
curl	-sS \
	-H "Accept: application/vnd.github+json" \
	-H "Authorization: Bearer $GITHUB_PAT" \
	-H "X-GitHub-Api-Version: 2026-03-10" \
	https://api.github.com/repos/$OWNER/$REPO/actions/runners)

echo RET $?

if echo "$output" | grep 'status.*401'; then
	echo "Expired token"
	exit 1
fi

echo "$output" | jq -r '.runners[] | "\(.name)   \(.id)   \(.status)  active=\(.busy)"' | column -t

