#!/bin/sh

echo do not run
exit 1

if [ -z "$1" ]; then
	echo "ERROR: give me worker number"
	exit 1
fi

NAME="runner$1"
OWNER="btrfs"
REPO="linux"
RURL="https://github.com/$OWNER/$REPO"
IMAGE="ghcr.io/actions/actions-runner:latest"
RHOME="/home/runner"
RWORK="$RHOME/_work"
LWORK="work-$NAME"
LWORKABS=$(readlink -f "$LWORK")

# Create token: https://github.com/btrfs/linux/settings/actions/runners/new
# ./config.sh --unattended --url "$URL" --name "$NAME" --token "$token"
# ./config.sh --url "$URL" --token "$token" --name "$NAME" --unattended
echo ./config.sh --url "URL" --token "token" --name "$NAME" --unattended

#IMAGE="runner0-checkpoint:latest"

mkdir -p "$LWORK"
sudo chown 1001:1001 -R "$LWORK"

docker run -it --name "$NAME" \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-v "$LWORKABS":"$RWORK" \
	--ulimit nofile=65536:65536 \
	--device /dev/kvm:/dev/kvm:rwm \
	"$IMAGE" \
	/bin/bash
