#!/bin/sh

nr=9
guestname=fstests/gh${nr}
gitdir=/mnt/workspace/linux-vm-nord/

cpu=2
mem=2G

drives=9
cache=writeback
blkif=virtio
cleandisk=true
drivefallocate=true
drivesize=12G

telnetport=$((9900+${nr}))
sshport=$((2200+${nr}))
serial=file:serial${nr}-$(date +%F_%T).log
serial=stdio

cleandisk=true

export fallocate
fallocate=true
drivefallocate=true
